version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: ktlint
          command: ./gradlew ktlint

      - run:
          name: detekt
          command: ./gradlew detekt

      - run:
          name: detekt
          command: ./gradlew test