version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
    JVM_OPTS: -Xmx4g
    steps:
      - checkout

      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTestCoverage
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results